name: 💡 Feature Request
description: Have an idea to improve MBuild?
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Your Idea
      description: What feature would you like to see?
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why?
      description: How would this improve the plugin or your server experience?
